### ISSUE TITLE
"beautify" option is deprecated in mjml-core and only available in mjml cli.

### ISSUE THREAD

**Issue by liran-co** [stidges/laravel-mix-mjml#10]
This doesn't seem to be compatible with the latest version of MJML. It throws the following error when compiling: 

```"beautify" option is deprecated in mjml-core and only available in mjml cli.```

**Comment by oliva1337** [comment]
same here

**Comment by thisisparth** [comment]
Same here. Any workaround?

**Comment by RoboWeb** [comment]
There is a workaround, but not resolve all problems...
```
mix.mjml(input, output, { 
  mjmlOptions: { beautify: false }
}
```

but after that:
`TypeError: Cannot read properties of undefined (reading 'getAssets') ...`

**Comment by stidges** [comment]
Sorry for the delay on this. MJML has deprecated these options since v4, so I've published a new version that removes the defaults from the plugin! Since this is a breaking change I've published a new major version, you can review the release notes [here](https://github.com/stidges/laravel-mix-mjml/releases/tag/v4.0.0)
